source "https://rubygems.org"

gem "rails", "~> 8.1.1"
gem "sqlite3", ">= 2.1"
gem "puma", ">= 5.0"

# Subflag Rails SDK - self-hosted with ActiveRecord backend
gem "subflag-rails", "~> 0.5.0"

gem "rack-cors"

group :development, :test do
  gem "debug", require: "debug/prelude"
end
